### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by ThomasBullock** [tommyip/bootstrap-icons-vue#10]
Im finding many icons are missing from https://icons.getbootstrap.com/
Cant find 
rocket rocket-fill, rocket-takeoff, rocket-takeoff-fill, person-lock, person-lock, person-fill-lock
Im searching `icons.d.ts` in the source code using the PascalCase naming convention also searching tags.
Seems there not there...

**Comment by tommyip** [comment]
@ThomasBullock which installation method and package version are you using?

The icons you mentioned are present for me on both NPM and on cdns.

**Comment by ThomasBullock** [comment]
@tommyip Thanks for quick reply! Yes your right was using `1.8.1` Sorry didn't even think of it as our apps barely a month old! 
Thanks
