### ISSUE TITLE
ES module error

### ISSUE THREAD

**Issue by ThibaultVlacich** [tommyip/bootstrap-icons-vue#15]
I'm getting this error coming from this package:

> require is not defined in ES module scope, you can use import instead This file is being treated as an ES module because it has a '.js' file extension and './node_modules/bootstrap-icons-vue/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

I think it appeared with a Vite update, but I can't be really sure. Any idea if there's something I can do in my config to fix this, or if the package needs to be updated?

**Comment by tobiasquadflieg** [comment]
#14 I just add a new pr that should solve the issue.

**Comment by tommyip** [comment]
Just published v1.11.3 with @tobiasquadflieg's patch. @ThibaultVlacich does it fixes the issue?

**Comment by ThibaultVlacich** [comment]
Yes, it's fixed :) Thanks.
